export type WorldCupVenue = {
  id: string;
  venueName: string;
  commonName: string;
  city: string;
  municipality?: string;
  country: string;
  latitude: number;
  longitude: number;
  note: string;
};

export const WORLD_CUP_VENUES: WorldCupVenue[] = [
  {
    id: 'atlanta',
    venueName: 'Atlanta Stadium',
    commonName: 'Mercedes-Benz Stadium',
    city: 'Atlanta',
    country: 'United States',
    latitude: 33.7554,
    longitude: -84.4008,
    note: 'FIFA World Cup 2026 host venue in Atlanta, Georgia.',
  },
  {
    id: 'boston',
    venueName: 'Boston Stadium',
    commonName: 'Gillette Stadium',
    city: 'Boston',
    municipality: 'Foxborough',
    country: 'United States',
    latitude: 42.0909,
    longitude: -71.2643,
    note: 'FIFA host city is Boston; the stadium is in Foxborough, Massachusetts.',
  },
  {
    id: 'dallas',
    venueName: 'Dallas Stadium',
    commonName: 'AT&T Stadium',
    city: 'Dallas',
    municipality: 'Arlington',
    country: 'United States',
    latitude: 32.7473,
    longitude: -97.0945,
    note: 'FIFA host city is Dallas; the stadium is in Arlington, Texas.',
  },
  {
    id: 'guadalajara',
    venueName: 'Estadio Guadalajara',
    commonName: 'Estadio Akron',
    city: 'Guadalajara',
    municipality: 'Zapopan',
    country: 'Mexico',
    latitude: 20.6819,
    longitude: -103.4622,
    note: 'FIFA host city is Guadalajara; the stadium is in Zapopan, Jalisco.',
  },
  {
    id: 'houston',
    venueName: 'Houston Stadium',
    commonName: 'NRG Stadium',
    city: 'Houston',
    country: 'United States',
    latitude: 29.6847,
    longitude: -95.4107,
    note: 'FIFA World Cup 2026 host venue in Houston, Texas.',
  },
  {
    id: 'kansas-city',
    venueName: 'Kansas City Stadium',
    commonName: 'GEHA Field at Arrowhead Stadium',
    city: 'Kansas City',
    country: 'United States',
    latitude: 39.0489,
    longitude: -94.4839,
    note: 'FIFA World Cup 2026 host venue in Kansas City, Missouri.',
  },
  {
    id: 'los-angeles',
    venueName: 'Los Angeles Stadium',
    commonName: 'SoFi Stadium',
    city: 'Los Angeles',
    municipality: 'Inglewood',
    country: 'United States',
    latitude: 33.9535,
    longitude: -118.3392,
    note: 'FIFA host city is Los Angeles; the stadium is in Inglewood, California.',
  },
  {
    id: 'mexico-city',
    venueName: 'Mexico City Stadium',
    commonName: 'Estadio Azteca',
    city: 'Mexico City',
    country: 'Mexico',
    latitude: 19.3029,
    longitude: -99.1505,
    note: 'Opening match venue for FIFA World Cup 2026.',
  },
  {
    id: 'miami',
    venueName: 'Miami Stadium',
    commonName: 'Hard Rock Stadium',
    city: 'Miami',
    municipality: 'Miami Gardens',
    country: 'United States',
    latitude: 25.958,
    longitude: -80.2389,
    note: 'FIFA host city is Miami; the stadium is in Miami Gardens, Florida.',
  },
  {
    id: 'monterrey',
    venueName: 'Estadio Monterrey',
    commonName: 'Estadio BBVA',
    city: 'Monterrey',
    municipality: 'Guadalupe',
    country: 'Mexico',
    latitude: 25.6689,
    longitude: -100.2445,
    note: 'FIFA host city is Monterrey; the stadium is in Guadalupe, Nuevo Leon.',
  },
  {
    id: 'new-york-new-jersey',
    venueName: 'New York New Jersey Stadium',
    commonName: 'MetLife Stadium',
    city: 'New York New Jersey',
    municipality: 'East Rutherford',
    country: 'United States',
    latitude: 40.8135,
    longitude: -74.0745,
    note: 'Final venue for FIFA World Cup 2026.',
  },
  {
    id: 'philadelphia',
    venueName: 'Philadelphia Stadium',
    commonName: 'Lincoln Financial Field',
    city: 'Philadelphia',
    country: 'United States',
    latitude: 39.9008,
    longitude: -75.1675,
    note: 'FIFA World Cup 2026 host venue in Philadelphia, Pennsylvania.',
  },
  {
    id: 'sf-bay-area',
    venueName: 'San Francisco Bay Area Stadium',
    commonName: "Levi's Stadium",
    city: 'San Francisco Bay Area',
    municipality: 'Santa Clara',
    country: 'United States',
    latitude: 37.403,
    longitude: -121.97,
    note: 'FIFA host city is San Francisco Bay Area; the stadium is in Santa Clara, California.',
  },
  {
    id: 'seattle',
    venueName: 'Seattle Stadium',
    commonName: 'Lumen Field',
    city: 'Seattle',
    country: 'United States',
    latitude: 47.5952,
    longitude: -122.3316,
    note: 'FIFA World Cup 2026 host venue in Seattle, Washington.',
  },
  {
    id: 'toronto',
    venueName: 'Toronto Stadium',
    commonName: 'BMO Field',
    city: 'Toronto',
    country: 'Canada',
    latitude: 43.6332,
    longitude: -79.4186,
    note: 'FIFA World Cup 2026 host venue in Toronto, Ontario.',
  },
  {
    id: 'vancouver',
    venueName: 'Vancouver Stadium',
    commonName: 'BC Place',
    city: 'Vancouver',
    country: 'Canada',
    latitude: 49.2768,
    longitude: -123.1119,
    note: 'FIFA World Cup 2026 host venue in Vancouver, British Columbia.',
  },
];
