export type WorldCupVenue = {
  id: string;
  venueName: string;
  city: string;
  country: string;
  latitude: number;
  longitude: number;
  note: string;
};

export const WORLD_CUP_VENUES: WorldCupVenue[] = [
  {
    id: 'atlanta',
    venueName: 'Mercedes-Benz Stadium',
    city: 'Atlanta',
    country: 'United States',
    latitude: 33.749,
    longitude: -84.388,
    note: 'Georgia host city.',
  },
  {
    id: 'boston',
    venueName: 'Gillette Stadium',
    city: 'Boston',
    country: 'United States',
    latitude: 42.3601,
    longitude: -71.0589,
    note: 'New England host city.',
  },
  {
    id: 'dallas',
    venueName: 'AT&T Stadium',
    city: 'Dallas',
    country: 'United States',
    latitude: 32.7767,
    longitude: -96.797,
    note: 'Arlington/Dallas metro host city.',
  },
  {
    id: 'guadalajara',
    venueName: 'Estadio Akron',
    city: 'Guadalajara',
    country: 'Mexico',
    latitude: 20.6597,
    longitude: -103.3496,
    note: 'Jalisco host city.',
  },
  {
    id: 'houston',
    venueName: 'NRG Stadium',
    city: 'Houston',
    country: 'United States',
    latitude: 29.7604,
    longitude: -95.3698,
    note: 'Texas Gulf Coast host city.',
  },
  {
    id: 'kansas-city',
    venueName: 'Arrowhead Stadium',
    city: 'Kansas City',
    country: 'United States',
    latitude: 39.0997,
    longitude: -94.5786,
    note: 'Midwest host city.',
  },
  {
    id: 'los-angeles',
    venueName: 'SoFi Stadium',
    city: 'Los Angeles',
    country: 'United States',
    latitude: 33.9416,
    longitude: -118.4085,
    note: 'Southern California host city.',
  },
  {
    id: 'mexico-city',
    venueName: 'Estadio Azteca',
    city: 'Mexico City',
    country: 'Mexico',
    latitude: 19.4326,
    longitude: -99.1332,
    note: 'Opening match city.',
  },
  {
    id: 'miami',
    venueName: 'Hard Rock Stadium',
    city: 'Miami',
    country: 'United States',
    latitude: 25.7617,
    longitude: -80.1918,
    note: 'Florida host city.',
  },
  {
    id: 'monterrey',
    venueName: 'Estadio BBVA',
    city: 'Monterrey',
    country: 'Mexico',
    latitude: 25.6866,
    longitude: -100.3161,
    note: 'Nuevo León host city.',
  },
  {
    id: 'new-york',
    venueName: 'MetLife Stadium',
    city: 'New York / New Jersey',
    country: 'United States',
    latitude: 40.7282,
    longitude: -74.0776,
    note: 'Final venue.',
  },
  {
    id: 'philadelphia',
    venueName: 'Lincoln Financial Field',
    city: 'Philadelphia',
    country: 'United States',
    latitude: 39.9526,
    longitude: -75.1652,
    note: 'Pennsylvania host city.',
  },
  {
    id: 'sf-bay-area',
    venueName: "Levi's Stadium",
    city: 'San Francisco Bay Area',
    country: 'United States',
    latitude: 37.3541,
    longitude: -121.9552,
    note: 'Santa Clara host city.',
  },
  {
    id: 'seattle',
    venueName: 'Lumen Field',
    city: 'Seattle',
    country: 'United States',
    latitude: 47.6062,
    longitude: -122.3321,
    note: 'Pacific Northwest host city.',
  },
  {
    id: 'toronto',
    venueName: 'BMO Field',
    city: 'Toronto',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    note: 'Ontario host city.',
  },
  {
    id: 'vancouver',
    venueName: 'BC Place Vancouver',
    city: 'Vancouver',
    country: 'Canada',
    latitude: 49.2827,
    longitude: -123.1207,
    note: 'British Columbia host city.',
  },
];
